[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kibana-logs-backend"
version = "0.1.0"
description = "API para procesar CSV de logs Kibana"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "fastapi==0.115.2",
  "uvicorn[standard]==0.32.0",
  "pandas==2.2.3",
  "python-multipart==0.0.12",
  "pydantic==2.9.2",
  "aio-pika==9.5.4"
]

[project.optional-dependencies]
dev = [
  "pytest==8.3.3",
  "httpx==0.27.2"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
